# Setup
title:               Frederic 的博客
tagline:             'Keep thinking, keep writing'
description:         '记录一些有用的和有趣的事情。'
url:                 http://zhoufei.io
baseurl:             ''
paginate:            10
permalink:           pretty

# About/contact
author:
  name:              Zhoufei(Frederic)
  url:               https://twitter.com/fredericzhou_io
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
