# Setup
title:               Frederic Zhou
tagline:             'Blog'
description:         'Keep thinking!! 写写画画'
url:                 http://zhoufei.io
baseurl:             ''
paginate:            10
permalink:           pretty

# About/contact
author:
  name:              Frederic Zhou
  url:               https://twitter.com/fredericzhou_io
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
